export * from './usuario.repository';
export * from './organizacion.repository';
export * from './rol.repository';
export * from './proyecto-de-construccion.repository';
export * from './destino-funcional.repository';
export * from './tipo-obra.repository';
export * from './provincia.repository';
export * from './propietario.repository';
export * from './proyectista.repository';
